# Generated by Django 2.1.7 on 2019-02-23 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('category', models.IntegerField()),
                ('availability', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('tableNumber', models.IntegerField()),
                ('done', models.BooleanField(default=False)),
                ('orderTime', models.DateTimeField(auto_now_add=True)),
                ('finishTime', models.DateTimeField(auto_now=True)),
                ('menuID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webserver.Menu')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webserver.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='sellerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webserver.Seller'),
        ),
        migrations.AddField(
            model_name='menu',
            name='sellerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webserver.Seller'),
        ),
    ]
